on: push
name: npm build, lint, test and publish
# jobs:
#   build-and-publish:
#     name: build and publish
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: npm install
#         uses: actions/npm@master
#         with:
#           args: install
#       - name: npm test
#         uses: actions/npm@master
#         with:
#           args: run test
#       - name: npm lint
#         uses: actions/npm@master
#         with:
#           args: run lint

#   build-docker:
#     name: build and publish
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: docker build
#         uses: actions/docker/cli@master
#         with:
#           args: build -t test .

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest]
        environment: [build, docker]
    runs-on: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install
        if: ${{ github.event.inputs.environment == 'docker' || (matrix.environment == 'build') }}
        run: npm install
      - name: lint
        if: ${{ github.event.inputs.environment == 'docker' || (matrix.environment == 'build') }}
        run: npm lint
      - name: test
        if: ${{ github.event.inputs.environment == 'docker' || (matrix.environment == 'build') }}
        run: npm test
      - name: Docker
        if: ${{ github.event.inputs.environment == 'docker' || (matrix.environment == 'build') }}
        uses: actions/docker/cli@master
        with:
          args: build -t test .